watch:
  cities:
    - name: "Raleigh"
      timezone: "America/New_York"
      flag: "🇺🇸"
    - name: "Göteborg"
      timezone: "Europe/Stockholm"
      flag: "🇸🇪"
    - name: "Nice"
      timezone: "Europe/Paris"
      flag: "🇫🇷"
    - name: "Tel Aviv"
      timezone: "Asia/Tel_Aviv"
      flag: "🇮🇱"
    - name: "Brno"
      timezone: "Europe/Prague"
      flag: "🇨🇿"
    - name: "Madrid"
      timezone: "Europe/Madrid"
      flag: "🇪🇸"
    - name: "Berlin"
      timezone: "Europe/Berlin"
      flag: "🇩🇪"
    - name: "Los Angeles"
      timezone: "America/Los_Angeles"
      flag: "🇺🇸"
    - name: "Melbourne"
      timezone: "Australia/Melbourne"
      flag: "🇦🇺"
