weather:
  city: "Dehradun"

gmail:
  credentials_file: "~/.config/tsk/work_credentials.json"
  token_file: "~/.config/nook/gmail_token.json"

calendar:
  credentials_file: "~/.config/tsk/work_credentials.json"
  token_file: "~/.config/tsk/work_token.json"
  calendars:
    - id: "akpant@redhat.com"
      name: "Me"
    - id: "OpenShift Pipelines"
      name: "OSP"
    - id: "eedri-all"
      name: "SF"

watch:
  cities:
    - name: "Raleigh"
      timezone: "America/New_York"
      flag: "🇺🇸"
    - name: "Göteborg"
      timezone: "Europe/Stockholm"
      flag: "🇸🇪"
    - name: "Nice"
      timezone: "Europe/Paris"
      flag: "🇫🇷"
    - name: "Raanana"
      timezone: "Asia/Jerusalem"
      flag: "🇮🇱"
    - name: "Brno"
      timezone: "Europe/Prague"
      flag: "🇨🇿"
    - name: "Madrid"
      timezone: "Europe/Madrid"
      flag: "🇪🇸"
    - name: "Berlin"
      timezone: "Europe/Berlin"
      flag: "🇩🇪"
    - name: "London"
      timezone: "Europe/London"
      flag: "🇬🇧"
    - name: "Melbourne"
      timezone: "Australia/Melbourne"
      flag: "🇦🇺"

apps:
  - com.slack.Slack
  - org.gnome.Ptyxis
  - dev.zed.Zed
  - com.brave.Browser
  - org.mozilla.firefox
